routes:
- origin: MAD
  destination: BCN
  max_price: 40
  currency: EUR
  departure_month: 2026-11
  return_month: 2026-11
- origin: MAD
  destination: LIS
  max_price: 60
  currency: EUR
  departure_month: 2026-11
  return_month: 2026-11
